import mongoose from 'mongoose';

const imageRecognitionSchema = new mongoose.Schema({
  product: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Product'
  },
  imageUrl: {
    type: String,
    required: true
  },
  uploadedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  analysis: {
    tags: [{
      name: String,
      confidence: Number,
      category: String
    }],
    objects: [{
      name: String,
      boundingBox: {
        x: Number,
        y: Number,
        width: Number,
        height: Number
      },
      confidence: Number
    }],
    colors: [{
      hex: String,
      rgb: {
        r: Number,
        g: Number,
        b: Number
      },
      percentage: Number,
      name: String
    }],
    text: [{
      content: String,
      language: String,
      confidence: Number
    }],
    faces: [{
      boundingBox: mongoose.Schema.Types.Mixed,
      attributes: {
        age: Number,
        gender: String,
        emotion: String
      }
    }],
    scenes: [{
      name: String,
      confidence: Number
    }],
    attributes: {
      style: String,
      pattern: String,
      material: String,
      brand: String,
      condition: String
    }
  },
  categorization: {
    primaryCategory: String,
    subCategories: [String],
    confidence: Number
  },
  autoGeneratedTitle: String,
  autoGeneratedDescription: String,
  suggestedTags: [String],
  similarProducts: [{
    product: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Product'
    },
    similarity: Number
  }],
  qualityScore: {
    overall: Number,
    resolution: Number,
    lighting: Number,
    clarity: Number,
    composition: Number
  },
  aiModel: {
    name: String,
    version: String,
    provider: {
      type: String,
      enum: ['google_vision', 'aws_rekognition', 'azure_vision', 'clarifai', 'custom']
    }
  },
  processingTime: Number, // milliseconds
  status: {
    type: String,
    enum: ['processing', 'completed', 'failed'],
    default: 'processing'
  },
  error: String
}, {
  timestamps: true
, suppressReservedKeysWarning: true });

// Indexes
imageRecognitionSchema.index({ product: 1 });
imageRecognitionSchema.index({ 'analysis.tags.name': 1 });
imageRecognitionSchema.index({ status: 1 });

const ImageRecognition = mongoose.model('ImageRecognition', imageRecognitionSchema);
export default ImageRecognition;
export { ImageRecognition };
