import mongoose from 'mongoose';

const productCategorizationSchema = new mongoose.Schema({
  product: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Product',
    required: true
  },
  autoGeneratedTags: [{
    tag: String,
    confidence: {
      type: Number,
      min: 0,
      max: 1
    },
    source: {
      type: String,
      enum: ['image_analysis', 'text_analysis', 'behavior_analysis', 'manual'],
      default: 'text_analysis'
    }
  }],
  categories: [{
    category: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Category'
    },
    confidence: Number,
    isPrimary: Boolean
  }],
  attributes: [{
    key: String,
    value: String,
    confidence: Number
  }],
  imageAnalysis: {
    dominantColors: [String],
    detectedObjects: [String],
    style: String,
    season: String,
    occasion: String
  },
  textAnalysis: {
    keywords: [String],
    sentiment: String,
    language: String
  },
  lastAnalyzed: {
    type: Date,
    default: Date.now
  },
  needsReview: {
    type: Boolean,
    default: false
  },
  reviewedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  reviewedAt: Date
}, {
  timestamps: true
, suppressReservedKeysWarning: true });

productCategorizationSchema.index({ product: 1 });
productCategorizationSchema.index({ 'autoGeneratedTags.tag': 1 });
productCategorizationSchema.index({ lastAnalyzed: 1 });

export default mongoose.model('ProductCategorization', productCategorizationSchema);
